// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgres://7822e1358e63c0a8ff349e5b2389a611e95321bad375f94f7fd9857ffee24a69:sk_PvocnCFlEnpiSsv-2yBfP@db.prisma.io:5432/postgres?sslmode=require",
    // url: process.env["DATABASE_URL"],
  },
});
